# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b4f7ff549b0bdd4f71a874d483f7f314d474c779b9d062b72ec2d32d6f2ddcf431d90c2e60064145587c570cb14a135ed310815b4e23a807bbfacede7d81f01

test:
  secret_key_base: 1f895a552ca620590be47383a3311e28d8c644f0ed8abf3ce734ad7c090670e5afd40c7d7db4064d6201effeb3cb546964df1781bcb64f65d59e406907fb7108

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
